# This is a basic workflow to help you get started with Actions

name: CI Build/Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: 
      - develop
      - feature/develop/task2
  pull_request:
    branches: 
      - develop
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
       # Install Arduino CLI 
      - name: Set up Arduino
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          tar -xvf arduino-cli_latest_Linux_64bit.tar.gz
          sudo mv arduino-cli /usr/local/bin/
          arduino-cli config init
      - name: Add ESP8266 package
        run: |
          arduino-cli config set board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          
      - name: Install ESP8266
        run: |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266  # Install the ESP8266 core

      - name: Compile Arduino Sketch for NodeMCU v3 wifi
        run: |
          mkdir -p build  # Ensure the build directory exists
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 --output-dir build ESP8266_CH340/ESP8266_CH340.ino
          
      # Collect binaries as artifacts
      - name: Upload binaries reports
        uses: actions/upload-artifact@v3
        with:
          name: compiled-files
          path: build/*.bin 

      # Collect test results as artifacts
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports/results.xml
